var css = {
    standard: "<p style='"
        + "font-size:medium;"
        + "background-color:#ffaaaa;"
        + "padding:4px;"
        + "padding-left:6px;"
        + "margin:0px;"
        + "border-radius:12px;"
        + "' />",
    spanEnd: "</p>",
    error: "<p style='"
        + "font-size:medium;"
        + "color:red;"
        + "' />",
    meleeResult: "<p style='"
        + "font-size:medium;"
        + "background-color:#440027;"
        + "color:white;"
        + "padding:4px;"
        + "padding-left:6px;"
        + "margin:0px;"
        + "border-radius:12px;"
        + "' />",
    attack: "<p style='"
        + "font-size:medium;"
        + "background-color:#cd88af;"
        + "padding:4px;"
        + "padding-left:6px;"
        + "margin:0px;"
        + "border-radius:12px;"
        + "' />",
    magicItem: "<p style='"
        + "font-size:medium;"
        + "background-color:#545500;"
        + "color:#fefeaa;"
        + "padding:4px;"
        + "padding-left:6px;"
        + "margin:0px;"
        + "border-radius:12px;"
        + "' />",
    counterAttack: "<p style='"
        + "font-size:medium;"
        + "background-color:#aa5585;"
        + "color:lightgrey;"
        + "padding:4px;"
        + "padding-left:6px;"
        + "margin:0px;"
        + "border-radius:12px;"
        + "' />",
    morale: "<p style='"
        + "font-size:medium;"
        + "background-color:#343477;"
        + "color:#ffffaa;"
        + "padding:4px;"
        + "padding-left:6px;"
        + "margin:0px;"
        + "border-radius:12px;"
        + "' />",
    missile: "<p style='"
        + "font-size:medium;"
        + "background-color:#ffaaaa;"
        + "padding:4px;"
        + "padding-left:6px;"
        + "margin:0px;"
        + "border-radius:12px;"
        + "' />",
    indirectMissile: "<p style='"
        + "font-size:medium;"
        + "background-color:#a5c663;"
        + "padding:4px;"
        + "padding-left:6px;"
        + "margin:0px;"
        + "border-radius:12px;"
        + "' />",
    missileDamage: "<p style='"
        + "font-size:medium;"
        + "background-color:#440027;"
        + "color:white;"
        + "padding:4px;"
        + "padding-left:6px;"
        + "margin:0px;"
        + "border-radius:12px;"
        + "' />",
    killValue: "<span style='"
        + "font-size:medium;"
        + "background-color:black;"
        + "color:yellow;"
        + "padding:3px;"
        + "' />",
    endValue: "</span>",
    rollValue: "<span style='"
        + "font-size:medium;"
        + "background-color:white;"
        + "color:black;"
        + "padding:5px;"
        + "border:thin solid black;"
        + "' />"

};


